image: jekyll/builder

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8


test:
  stage: test
  script:
  - bundle update
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle update
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master